export const user = {
    REGISTER_WITH_EMAIL: 'REGISTER_WITH_EMAIL',
    REGISTER_WITH_PHONE: 'REGISTER_WITH_PHONE',
    GET_USER_INFO_BY_ID: 'GET_USER_INFO_BY_ID',
    LOGIN_WITH_EMAIL: 'LOGIN_WITH_EMAIL',
    LOGOUT: 'LOGOUT',
};